name: music_notes
description: Music notes library
version: 0.4.0

repository: https://github.com/albertms10/music_notes.git

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  collection: any
  meta: any
  test: ^1.24.1

dev_dependencies:
  dart_code_metrics: ^5.7.1
  very_good_analysis: ^4.0.0+1
