name: music_notes
description: A comprehensive Dart library for effortlessly working with music
  theory concepts.
version: 0.23.0

repository: https://github.com/albertms10/music_notes
topics:
  - music
  - music-theory
  - music-notation
  - education
  - midi

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  meta: ^1.17.0
  xml: ^6.6.1

dev_dependencies:
  test: ^1.28.0
  very_good_analysis: ^10.0.0
