name: music_notes
description: Music notes library
version: 0.10.0

repository: https://github.com/albertms10/music_notes.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: any
  meta: any
  test: any

dev_dependencies:
  dart_code_metrics: ^5.7.5
  very_good_analysis: ^5.0.0+1
