name: music_notes
description: A comprehensive Dart library for effortlessly working with music
  theory concepts.
version: 0.18.0

repository: https://github.com/albertms10/music_notes
topics:
  - music
  - music-theory
  - music-notation
  - education
  - midi

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  meta: ^1.12.0

dev_dependencies:
  test: ^1.25.5
  very_good_analysis: ">=5.1.0 <7.0.0"
