name: music_notes
description: Comprehensive set of utilities for working with music theory concepts.
version: 0.17.0

repository: https://github.com/albertms10/music_notes.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  meta: ^1.11.0

dev_dependencies:
  test: ^1.25.2
  very_good_analysis: ^5.1.0
