name: music_notes
description: Music notes library
version: 0.1.0

repository: https://github.com/albertms10/music_notes.git

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  collection: ^1.15.0
  meta: ^1.7.0
  quiver: ^3.0.1
  test: ^1.16.5

dev_dependencies:
  test_coverage: ^0.5.0
  very_good_analysis: ^2.3.0
