name: music_notes
description: A comprehensive Dart library for effortlessly working with music
  theory concepts.
version: 0.17.1

repository: https://github.com/albertms10/music_notes.git
issue_tracker: https://github.com/albertms10/music_notes/issues
topics:
  - music
  - music-theory
  - notation
  - education
  - midi

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  meta: ^1.11.0

dev_dependencies:
  test: ^1.25.2
  very_good_analysis: ^5.1.0
