name: music_notes
description: Comprehensive set of utilities for working with music theory concepts.
version: 0.12.0

repository: https://github.com/albertms10/music_notes.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  meta: ^1.9.1
  test: ^1.24.1

dev_dependencies:
  benchmark_harness: ^2.2.2
  very_good_analysis: ^5.0.0+1
